// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo4A1Xa39akq5okoLnSkm1MDbj9yonbBg',
    appId: '1:355601821000:web:08b80f3e78445ccd99177d',
    messagingSenderId: '355601821000',
    projectId: 'flutter-ui-6da2a',
    authDomain: 'flutter-ui-6da2a.firebaseapp.com',
    storageBucket: 'flutter-ui-6da2a.appspot.com',
    measurementId: 'G-PLW0GKVZ1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJ9mZkDJesoruhkB3gmblL7EprPJHHYg',
    appId: '1:355601821000:android:4a10ef796783197699177d',
    messagingSenderId: '355601821000',
    projectId: 'flutter-ui-6da2a',
    storageBucket: 'flutter-ui-6da2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxn7QnKOtJmJO-iTsI-VipkN2wMcK3ECg',
    appId: '1:355601821000:ios:4a99e43bf361e7c899177d',
    messagingSenderId: '355601821000',
    projectId: 'flutter-ui-6da2a',
    storageBucket: 'flutter-ui-6da2a.appspot.com',
    iosClientId: '355601821000-ti23ndpoeilmb6pppasb132bqfco0k9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxn7QnKOtJmJO-iTsI-VipkN2wMcK3ECg',
    appId: '1:355601821000:ios:4a99e43bf361e7c899177d',
    messagingSenderId: '355601821000',
    projectId: 'flutter-ui-6da2a',
    storageBucket: 'flutter-ui-6da2a.appspot.com',
    iosClientId: '355601821000-ti23ndpoeilmb6pppasb132bqfco0k9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
